package org.openshift.quickstarts.decisionserver.hellorules

query "get greeting"()
    greeting : Greeting()
end

rule "greet master"
    when
        person : Person( name == "rettori")
    then
        String salutation = "Hello " + person.getName() + "! Jenkins github testing for OSE33 CICD pipeline : Trial 3 by....Geeereeee33333333";
        insert(new Greeting(salutation));
end
rule "greet strangers"
    when
        person : Person( name != "rettori")
    then
        String salutation = "hi there, trial with Giri, testing githook, get out of my way OSE I have arrived " + person.getName();
        insert(new Greeting(salutation));
end
