package openshift.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyTable implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MyTable() {
        //"blalala"
    }

}